
server:
  port: 1002

spring:
  #  cloud:
  #    alibaba:
  #      seata:
  #        tx-service-group: my_tx_group
  application:
    name: two


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-rm-two?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

#logging:
#  level:
#    root: debug
